name: call_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  pinput: ^5.0.1
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  google_fonts: ^6.3.0
  equatable: ^2.0.7

  shared_preferences: ^2.5.3
  call_log: ^6.0.0
  android_intent_plus: ^5.3.0
  device_info_plus: ^11.5.0
  intl: ^0.20.2
  flutter_background_service: ^5.1.0
  flutter_overlay_window: ^0.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 800
