name: call_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  pinput: ^5.0.1
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  google_fonts: ^6.3.0
  equatable: ^2.0.7
  google_sign_in: ^6.2.1
  overlay_support: ^1.2.1
  phone_state: ^2.1.1                  # For phone state monitoring
  flutter_background_service: ^5.1.0    # For background service
  flutter_overlay_window: ^0.4.5

  shared_preferences: ^2.5.3
  call_log: ^6.0.0
  android_intent_plus: ^5.3.0
  device_info_plus: ^11.5.0
  intl: ^0.20.2
  app_settings: ^6.1.1
  flutter_local_notifications: ^19.4.0
  usage_stats: ^1.3.1
  installed_apps: ^1.6.0
  hive_flutter: ^1.1.0
  system_alert_window: ^2.0.7
  flutter_background_service_android: ^6.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
flutter_icons:
  android: "ic_stat_callman"
  ios: true
  image_path: "assets/icon/notification_icon.png"

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 800
